POST http://localhost:3000/product HTTP/1.1
Content-Type: application/json

{
    "nombre": "AutdoID4sds",
    "marca": "",
    "pActivo": "pruebanombre",
    "enfermedad": "pruebanombre",
    "idImagen": "pruebanombre"
}

###
PUT http://localhost:3000/product/677f128bd02cabbd8d794cea HTTP/1.1
Content-Type: application/json

{
    "estado": "IN_USE"
}

###
GET http://localhost:3000/product/ HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3000/product/677f128bd02cabbd8d794cea HTTP/1.1
Content-Type: application/json



###
DELETE  http://localhost:3000/product/677f128bd02cabbd8d794cea HTTP/1.1
Content-Type: application/json

