POST http://localhost:3000/product HTTP/1.1
Content-Type: application/json

{
    "idproducto": 1,
    "nombre": 1,
    "marca": "pruebanombre",
    "Pactivo": "pruebanombre",
    "Enfermedad": "pruebanombre",
    "idImagen": "pruebanombre"
}